classDiagram
    %% === CLASSES ===
    class Administrator {
        -adminId: String
        -name: String
        -email: String
        +addUser()
        +removeUser()
        +viewLogs()
    }

    class User {
        -userId: String
        -username: String
        -role: String
        -email: String
        +requestAccess()
        +reportIssue()
    }

    class Device {
        -deviceId: String
        -deviceName: String
        -ipAddress: String
        -status: String
        -location: String
        +updateStatus()
        +rebootDevice()
    }

    class MonitoringAgent {
        -agentId: String
        -name: String
        -version: String
        -status: String
        +monitorTraffic()
        +generateReport()
    }

    class AccessRequest {
        -requestId: String
        -userId: String
        -deviceId: String
        -timestamp: Date
        -status: String
        +approveRequest()
        +denyRequest()
    }

    class Log {
        -logId: String
        -timestamp: Date
        -action: String
        -userId: String
        -severity: String
        +archiveLog()
    }

    %% === RELATIONSHIPS WITH MULTIPLICITY ===

    %% Admin manages many Users (Association)
    Administrator "1" --> "0..*" User : manages

    %% User submits many AccessRequests (Association)
    User "1" --> "0..*" AccessRequest : submits

    %% AccessRequest targets one Device (Association)
    AccessRequest "1" --> "1" Device : for

    %% AccessRequest submitted by one User (Association)
    AccessRequest "1" --> "1" User : by

    %% User accesses many Devices (Association)
    User "1" --> "0..*" Device : accesses

    %% Agent monitors multiple Devices (Aggregation)
    MonitoringAgent "1" o-- "1..*" Device : monitors

    %% Logs generated by User (Association)
    User "1" --> "0..*" Log : logsActivity

    %% Logs generated by Admin (Association)
    Administrator "1" --> "0..*" Log : logsAction

    %% Notes
    note for Device "Devices are monitored and accessed if they are in 'active' status."
